server.port=8080
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.iobkfuerhmwyntbskmhc
spring.datasource.password=HRelperPass1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=L52aDMjYpD1UllHNJxk38o20jcKuG1dZ0EkjLg5nGUF